<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	  <PackageId>hellojay</PackageId>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
	  <PackAsTool>true</PackAsTool>
	  <ToolCommandName>hellojay</ToolCommandName>
	  <Version>1.0.1</Version>
	  <Authors>Jayakrishnan.Parameswarankutty</Authors>
	  <Description>Jay Terminal developer card crafted while learning to code.</Description>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
